# Generated by Django 3.2.3 on 2021-07-17 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
