# Generated by Django 3.2.3 on 2021-08-21 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210731_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
